image:
  file: .gitpod.Dockerfile
tasks:
  - name: Clippy
    init: cargo clippy --all-targets --all-features -- -D warnings
  - name: Test
    init: cargo test --all --all-features
  - name: Build
    init: cargo build 